{{- if not .Values.cloudflare.existingSecret }}
{{- if not .Values.cloudflare.apiToken }}
{{- fail "Set cloudflare.apiToken or cloudflare.existingSecret" }}
{{- end }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "pikadns.fullname" . }}
  labels:
    {{- include "pikadns.labels" . | nindent 4 }}
type: Opaque
stringData:
  cf-api-token: {{ .Values.cloudflare.apiToken | quote }}
{{- end }}
